status = [
    "server_build (ubuntu-stable)",
    "server_build (ubuntu-beta)",
    "server_build (ubuntu-nightly)",
    "server_test (ubuntu-stable)",
    "server_test (ubuntu-beta)",
    "server_test (ubuntu-nightly)",
    "server_fmt",
    "server_clippy (ubuntu-stable)",
    "server_clippy (ubuntu-beta)",
    "server_clippy (ubuntu-nightly)",
    "server_coverage",
    "server_security_audit",
]
delete_merged_branches = true
timeout_sec = 1200 # 20 min
