name: Server Build

on:
  push:
    branches: [ main, staging, trying ]
  pull_request:
    branches: [ main ]

jobs:
  server_build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [ ubuntu-stable, ubuntu-beta, ubuntu-nightly ]

        include:
          - build: ubuntu-stable
            os: ubuntu-latest
            rust: stable

          - build: ubuntu-beta
            os: ubuntu-latest
            rust: beta

          - build: ubuntu-nightly
            os: ubuntu-latest
            rust: nightly

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --manifest-path server/Cargo.toml
