name: Server Test

on:
  push:
    branches: [ main, staging, trying ]
  pull_request:
    branches: [ main ]

jobs:
  server_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [ ubuntu-stable, ubuntu-beta, ubuntu-nightly ]

        include:
          - build: ubuntu-stable
            os: ubuntu-latest
            rust: stable

          - build: ubuntu-beta
            os: ubuntu-latest
            rust: beta

          - build: ubuntu-nightly
            os: ubuntu-latest
            rust: nightly

    steps:
      - uses: actions/checkout@v2

      - name: Setting up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: test (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path server/Cargo.toml

      - name: test (serial feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features serial --manifest-path server/Cargo.toml
